### ISSUE TITLE
Unable to complete commit

### ISSUE THREAD

**Issue by jess-shue** [forestgeo/fgeo.blog#14]
Hi, I'm receiving the following error with two blog posts listed that I don't wish to actually edit (not sure why they are causing an issue). 
>>> C:/Program Files/Git/bin/git.exe pull
error: Your local changes to the following files would be overwritten by merge:
	content/post/2018-02-08-update-r-rstudio-and-r-packages.html
	content/post/2018-03-15-how-to-read-data-safely-with-only-base-r.html
Please commit your changes or stash them before you merge.
Aborting

**Comment by maurolepore** [comment]
That's OK, try what you are promed to do:
> Please commit your changes.

So: 
* Commit whatever you have. 
* Pull.
* Push.

If you need to let me know and we can share screens.

**Comment by maurolepore** [comment]
The reason why this is appearing is because your local version of the project is behind what is now on GitHub. I may have made some changes on those files since the last time you pulled them from GitHub into your local branch.

**Comment by jess-shue** [comment]
Thanks, I had tried that before. I'm not sure that it worked properly, but I can see an updated version through posts.

**Comment by maurolepore** [comment]
Great! 

Yes, it seems that it worked. I can see that the latest changes on GitHub are those you pushed.

Well done.

![image](https://user-images.githubusercontent.com/5856545/38825451-9a417bbc-417a-11e8-8eb1-159a8b5c3a2a.png)

**Comment by jess-shue** [comment]
Great! Not sure why it gave me so much trouble previously. Thank you!

**Comment by maurolepore** [comment]
Git can be very frustrating, even for me. But it's so powerful that it pays
off. Try to stick with it if you can.

Cheers,
Mauro
